export const TEST_FORM_CHANGE = 'TEST_FORM_CHANGE'
export const TEST_REQUEST = 'TEST_REQUEST'
export const LOGIN_FORM_CHANGE = 'LOGIN_FORM_CHANGE'
export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'
export const INVALID_AUTH = 'INVALID_AUTH'
export const GET_USER_INFO = 'GET_USER_INFO'
